services:
  app:
    image: 'registry.cn-beijing.aliyuncs.com/sz-dev/nginx-proxy-manager-zh:latest'
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - sz-network
networks:
  sz-network:
    external: true