server {
    listen       9700;
    listen  [::]:9700;
    server_name  localhost;
    access_log /var/log/nginx/default.access.log;
    error_log /var/log/nginx/default.error.log;

    location /resource {
        alias /data/;
        autoindex off;   # 不想列目录就 off；想临时列目录可改 on
        try_files $uri $uri/ =404;
    }
}
